### ISSUE TITLE
Can't build this with docker-compose

### ISSUE THREAD

**Issue by oxyo** [iknowjason/hammer#10]
Getting this error:
ERROR: Service 'webapp' failed to build : The command '/bin/sh -c bundle install' returned a non-zero code: 7

**Comment by iknowjason** [comment]
Taking a look and should get this addressed soon.

**Comment by iknowjason** [comment]
I have fixed this issue with mimemagic.  Identified another issue so working on resolving all of them.  Reference here:https://github.com/mimemagicrb/mimemagic/issues/98

**Comment by iknowjason** [comment]
Fixed the issue and pushed a new commit with fix.  Feel free to test again @oxyo .

**Comment by oxyo** [comment]
Thank You. It build now fine, but getting this error in web app on localhost:3000:
`
ActiveRecord::NoDatabaseError
Unknown database 'rackvuln_development' 
![$screen_036](https://user-images.githubusercontent.com/304258/112734178-cf1cf500-8f4c-11eb-8780-8c6a8f41b375.png)
`

**Comment by iknowjason** [comment]
Yes, I had that same issue until I destroyed and rebuilt the container.  Give that a try.  As reference, I used some of these commands:  
https://colorfield.be/blog/cleaning-lando-containers

**Comment by iknowjason** [comment]
Didn't hear back on suggested fix to rebuild the container.  Closing.
